# Exported from Render on 2024-10-16T20:54:39Z
services:
  - type: web
    plan: free
    name: lamuela
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn djangoDeploy.wsgi"
